language: python

stages:
  - linting
  - test

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
    - "$HOME/.cache/pre-commit"

before_install:
  - if [ -n "$JYTHON" ]; then ./travis_jython.sh; fi
  - if [ -n "$JYTHON" ]; then export PYTHON_EXE=$HOME/jython/bin/python; else export PYTHON_EXE=python; fi
  - if [ -n "$JYTHON" ]; then export CLASSPATH=$HOME/jython/javalib/*; fi

install:
  - $PYTHON_EXE -m pip install pip -U
  - $PYTHON_EXE get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - poetry install -v

script: $PYTHON_EXE -m pytest -q tests/

jobs:
  include:
    - python: "2.7"
      env:
        - JYTHON=""
    - python: "2.7"
      env:    
        - JYTHON=org.python:jython-installer:2.7.1
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial

    - stage: linting
      python: "3.6"
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
